spring:
  rabbitmq:
    host: 192.168.213.133
    port: 5672
    username: zyy
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
        acknowledge-mode: manual #手动